const char html_content[] = 
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta charset=\"UTF-8\" />\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
"    <title>Date and Time Submission</title>\n"
"    <link rel=\"icon\" type=\"image/x-icon\" href=\"favicon.ico\" />\n"
"    <style>\n"
"      body {\n"
"        font-family: Arial, sans-serif;\n"
"        margin: 50px;\n"
"      }\n"
"      form {\n"
"        display: flex;\n"
"        flex-direction: column;\n"
"        width: 300px;\n"
"      }\n"
"      label {\n"
"        margin: 10px 0 5px;\n"
"      }\n"
"      input {\n"
"        padding: 8px;\n"
"        margin-bottom: 15px;\n"
"      }\n"
"      button {\n"
"        padding: 10px;\n"
"        background-color: #4caf50;\n"
"        color: white;\n"
"        border: none;\n"
"        cursor: pointer;\n"
"      }\n"
"    </style>\n"
"  </head>\n"
"  <body>\n"
"    <h1>Settings</h1>\n"
"    <!-- <a href=\"?led=0\">0</a>\n"
"    <a href=\"?led=1\">1</a> -->\n"
"    <form id=\"dateTimeForm\">\n"
"      <h2>Start Time</h2>\n"
"      <label for=\"startDate\">Date:</label>\n"
"      <input type=\"date\" id=\"startDate\" name=\"startDate\" required />\n"
"      <label for=\"startTime\">Time:</label>\n"
"      <input type=\"time\" id=\"startTime\" name=\"startTime\" required />\n"
"\n"
"      <h2>Birthday Time</h2>\n"
"      <label for=\"birthdayDate\">Date:</label>\n"
"      <input type=\"date\" id=\"birthdayDate\" name=\"birthdayDate\" required />\n"
"      <label for=\"birthdayTime\">Time:</label>\n"
"      <input type=\"time\" id=\"birthdayTime\" name=\"birthdayTime\" required />\n"
"      <button type=\"submit\">Submit</button>\n"
"    </form>\n"
"\n"
"    <script>\n"
"      const form = document.getElementById(\"dateTimeForm\");\n"
"\n"
"      form.addEventListener(\"submit\", async (event) => {\n"
"        event.preventDefault(); // Prevent page reload\n"
"        const now = new Date();\n"
"        const year = now.getFullYear();\n"
"        const month = String(now.getMonth() + 1).padStart(2, \"0\");\n"
"        const day = String(now.getDate()).padStart(2, \"0\");\n"
"        const hours = String(now.getHours()).padStart(2, \"0\");\n"
"        const minutes = String(now.getMinutes()).padStart(2, \"0\");\n"
"        const seconds = String(now.getSeconds()).padStart(2, \"0\");\n"
"        const currentDate = `${year}-${month}-${day}`;\n"
"        const currentTime = `${hours}:${minutes}:${seconds}`;\n"
"        const startDate = document.getElementById(\"startDate\").value;\n"
"        const startTime = document.getElementById(\"startTime\").value;\n"
"        const birthdayDate = document.getElementById(\"birthdayDate\").value;\n"
"        const birthdayTime = document.getElementById(\"birthdayTime\").value;\n"
"        const baseURL = window.location.origin + window.location.pathname;\n"
"        window.location.href = `${baseURL}?currentDate=${currentDate}&currentTime=${currentTime}&startDate=${startDate}&startTime=${startTime}&birthdayDate=${birthdayDate}&birthdayTime=${birthdayTime}`;\n"
"      });\n"
"    </script>\n"
"  </body>\n"
"</html>\n";
